### ISSUE TITLE
Cooldown feature

### ISSUE THREAD

**Issue by JasonG-FR** [GarlicoinForum/GoldenBot#18]
Someone abused the !help function to spam a channel, we need to set a limit to all commands for each user.

**Comment by JasonG-FR** [comment]
This happened again, we need something that check for multiple same queries in less than 1 minute.
If a second query happen before 1 min, send the reply by PM.
If more than 10 in less than 1 min spam the inbox? (STOP SPAMMING)

**Comment by trishmapow** [comment]
We need to bump this one - some child is ruining LWGRLCT constantly with this

**Comment by JasonG-FR** [comment]
Done
